export default {
  login: 'HabibIbrahimov',
  id: 91114210,
  node_id: 'MDQ6VXNlcjkxMTE0MjEw',
  avatar_url: 'https://avatars.githubusercontent.com/u/91114210?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/HabibIbrahimov',
  html_url: 'https://github.com/HabibIbrahimov',
  followers_url: 'https://api.github.com/users/HabibIbrahimov/followers',
  following_url:
    'https://api.github.com/users/HabibIbrahimov/following{/other_user}',
  gists_url: 'https://api.github.com/users/HabibIbrahimov/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/HabibIbrahimov/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/HabibIbrahimov/subscriptions',
  organizations_url: 'https://api.github.com/users/HabibIbrahimov/orgs',
  repos_url: 'https://api.github.com/users/HabibIbrahimov/repos',
  events_url: 'https://api.github.com/users/HabibIbrahimov/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/HabibIbrahimov/received_events',
  type: 'User',
  site_admin: false,
  name: 'Habib',
  company: 'Code Academy',
  blog: '',
  location: 'Baku',
  email: null,
  hireable: null,
  bio: 'Front-End Developer',
  twitter_username: null,
  public_repos: 77,
  public_gists: 0,
  followers: 13,
  following: 18,
  created_at: '2021-09-21T06:29:13Z',
  updated_at: '2023-01-31T16:48:50Z',
};
