export default [
  {
    login: 'Ulvi9',
    id: 64775437,
    node_id: 'MDQ6VXNlcjY0Nzc1NDM3',
    avatar_url: 'https://avatars.githubusercontent.com/u/64775437?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Ulvi9',
    html_url: 'https://github.com/Ulvi9',
    followers_url: 'https://api.github.com/users/Ulvi9/followers',
    following_url: 'https://api.github.com/users/Ulvi9/following{/other_user}',
    gists_url: 'https://api.github.com/users/Ulvi9/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Ulvi9/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Ulvi9/subscriptions',
    organizations_url: 'https://api.github.com/users/Ulvi9/orgs',
    repos_url: 'https://api.github.com/users/Ulvi9/repos',
    events_url: 'https://api.github.com/users/Ulvi9/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Ulvi9/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'niyazidageek',
    id: 82367001,
    node_id: 'MDQ6VXNlcjgyMzY3MDAx',
    avatar_url: 'https://avatars.githubusercontent.com/u/82367001?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/niyazidageek',
    html_url: 'https://github.com/niyazidageek',
    followers_url: 'https://api.github.com/users/niyazidageek/followers',
    following_url:
      'https://api.github.com/users/niyazidageek/following{/other_user}',
    gists_url: 'https://api.github.com/users/niyazidageek/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/niyazidageek/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/niyazidageek/subscriptions',
    organizations_url: 'https://api.github.com/users/niyazidageek/orgs',
    repos_url: 'https://api.github.com/users/niyazidageek/repos',
    events_url: 'https://api.github.com/users/niyazidageek/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/niyazidageek/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'afsanaa01',
    id: 90095968,
    node_id: 'MDQ6VXNlcjkwMDk1OTY4',
    avatar_url: 'https://avatars.githubusercontent.com/u/90095968?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/afsanaa01',
    html_url: 'https://github.com/afsanaa01',
    followers_url: 'https://api.github.com/users/afsanaa01/followers',
    following_url:
      'https://api.github.com/users/afsanaa01/following{/other_user}',
    gists_url: 'https://api.github.com/users/afsanaa01/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/afsanaa01/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/afsanaa01/subscriptions',
    organizations_url: 'https://api.github.com/users/afsanaa01/orgs',
    repos_url: 'https://api.github.com/users/afsanaa01/repos',
    events_url: 'https://api.github.com/users/afsanaa01/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/afsanaa01/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'gnlhmbtv',
    id: 91114086,
    node_id: 'MDQ6VXNlcjkxMTE0MDg2',
    avatar_url: 'https://avatars.githubusercontent.com/u/91114086?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gnlhmbtv',
    html_url: 'https://github.com/gnlhmbtv',
    followers_url: 'https://api.github.com/users/gnlhmbtv/followers',
    following_url:
      'https://api.github.com/users/gnlhmbtv/following{/other_user}',
    gists_url: 'https://api.github.com/users/gnlhmbtv/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gnlhmbtv/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gnlhmbtv/subscriptions',
    organizations_url: 'https://api.github.com/users/gnlhmbtv/orgs',
    repos_url: 'https://api.github.com/users/gnlhmbtv/repos',
    events_url: 'https://api.github.com/users/gnlhmbtv/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/gnlhmbtv/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'RasulRustamli',
    id: 91114148,
    node_id: 'MDQ6VXNlcjkxMTE0MTQ4',
    avatar_url: 'https://avatars.githubusercontent.com/u/91114148?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/RasulRustamli',
    html_url: 'https://github.com/RasulRustamli',
    followers_url: 'https://api.github.com/users/RasulRustamli/followers',
    following_url:
      'https://api.github.com/users/RasulRustamli/following{/other_user}',
    gists_url: 'https://api.github.com/users/RasulRustamli/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/RasulRustamli/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/RasulRustamli/subscriptions',
    organizations_url: 'https://api.github.com/users/RasulRustamli/orgs',
    repos_url: 'https://api.github.com/users/RasulRustamli/repos',
    events_url: 'https://api.github.com/users/RasulRustamli/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/RasulRustamli/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'TabrizHabiyev',
    id: 91114214,
    node_id: 'MDQ6VXNlcjkxMTE0MjE0',
    avatar_url: 'https://avatars.githubusercontent.com/u/91114214?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/TabrizHabiyev',
    html_url: 'https://github.com/TabrizHabiyev',
    followers_url: 'https://api.github.com/users/TabrizHabiyev/followers',
    following_url:
      'https://api.github.com/users/TabrizHabiyev/following{/other_user}',
    gists_url: 'https://api.github.com/users/TabrizHabiyev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/TabrizHabiyev/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/TabrizHabiyev/subscriptions',
    organizations_url: 'https://api.github.com/users/TabrizHabiyev/orgs',
    repos_url: 'https://api.github.com/users/TabrizHabiyev/repos',
    events_url: 'https://api.github.com/users/TabrizHabiyev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/TabrizHabiyev/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'SafaraliyevKamal',
    id: 91114217,
    node_id: 'MDQ6VXNlcjkxMTE0MjE3',
    avatar_url: 'https://avatars.githubusercontent.com/u/91114217?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/SafaraliyevKamal',
    html_url: 'https://github.com/SafaraliyevKamal',
    followers_url: 'https://api.github.com/users/SafaraliyevKamal/followers',
    following_url:
      'https://api.github.com/users/SafaraliyevKamal/following{/other_user}',
    gists_url: 'https://api.github.com/users/SafaraliyevKamal/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/SafaraliyevKamal/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/SafaraliyevKamal/subscriptions',
    organizations_url: 'https://api.github.com/users/SafaraliyevKamal/orgs',
    repos_url: 'https://api.github.com/users/SafaraliyevKamal/repos',
    events_url:
      'https://api.github.com/users/SafaraliyevKamal/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/SafaraliyevKamal/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'SabinKh',
    id: 91114252,
    node_id: 'MDQ6VXNlcjkxMTE0MjUy',
    avatar_url: 'https://avatars.githubusercontent.com/u/91114252?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/SabinKh',
    html_url: 'https://github.com/SabinKh',
    followers_url: 'https://api.github.com/users/SabinKh/followers',
    following_url:
      'https://api.github.com/users/SabinKh/following{/other_user}',
    gists_url: 'https://api.github.com/users/SabinKh/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/SabinKh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/SabinKh/subscriptions',
    organizations_url: 'https://api.github.com/users/SabinKh/orgs',
    repos_url: 'https://api.github.com/users/SabinKh/repos',
    events_url: 'https://api.github.com/users/SabinKh/events{/privacy}',
    received_events_url: 'https://api.github.com/users/SabinKh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Turaldi',
    id: 91114292,
    node_id: 'MDQ6VXNlcjkxMTE0Mjky',
    avatar_url: 'https://avatars.githubusercontent.com/u/91114292?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Turaldi',
    html_url: 'https://github.com/Turaldi',
    followers_url: 'https://api.github.com/users/Turaldi/followers',
    following_url:
      'https://api.github.com/users/Turaldi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Turaldi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Turaldi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Turaldi/subscriptions',
    organizations_url: 'https://api.github.com/users/Turaldi/orgs',
    repos_url: 'https://api.github.com/users/Turaldi/repos',
    events_url: 'https://api.github.com/users/Turaldi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Turaldi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'KmrnIsmylvv',
    id: 91727605,
    node_id: 'U_kgDOBXem9Q',
    avatar_url: 'https://avatars.githubusercontent.com/u/91727605?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/KmrnIsmylvv',
    html_url: 'https://github.com/KmrnIsmylvv',
    followers_url: 'https://api.github.com/users/KmrnIsmylvv/followers',
    following_url:
      'https://api.github.com/users/KmrnIsmylvv/following{/other_user}',
    gists_url: 'https://api.github.com/users/KmrnIsmylvv/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/KmrnIsmylvv/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/KmrnIsmylvv/subscriptions',
    organizations_url: 'https://api.github.com/users/KmrnIsmylvv/orgs',
    repos_url: 'https://api.github.com/users/KmrnIsmylvv/repos',
    events_url: 'https://api.github.com/users/KmrnIsmylvv/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/KmrnIsmylvv/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'thefidanabdulla',
    id: 95448022,
    node_id: 'U_kgDOBbBr1g',
    avatar_url: 'https://avatars.githubusercontent.com/u/95448022?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/thefidanabdulla',
    html_url: 'https://github.com/thefidanabdulla',
    followers_url: 'https://api.github.com/users/thefidanabdulla/followers',
    following_url:
      'https://api.github.com/users/thefidanabdulla/following{/other_user}',
    gists_url: 'https://api.github.com/users/thefidanabdulla/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/thefidanabdulla/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/thefidanabdulla/subscriptions',
    organizations_url: 'https://api.github.com/users/thefidanabdulla/orgs',
    repos_url: 'https://api.github.com/users/thefidanabdulla/repos',
    events_url: 'https://api.github.com/users/thefidanabdulla/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/thefidanabdulla/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'SiruzMammadli',
    id: 100166075,
    node_id: 'U_kgDOBfhpuw',
    avatar_url: 'https://avatars.githubusercontent.com/u/100166075?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/SiruzMammadli',
    html_url: 'https://github.com/SiruzMammadli',
    followers_url: 'https://api.github.com/users/SiruzMammadli/followers',
    following_url:
      'https://api.github.com/users/SiruzMammadli/following{/other_user}',
    gists_url: 'https://api.github.com/users/SiruzMammadli/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/SiruzMammadli/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/SiruzMammadli/subscriptions',
    organizations_url: 'https://api.github.com/users/SiruzMammadli/orgs',
    repos_url: 'https://api.github.com/users/SiruzMammadli/repos',
    events_url: 'https://api.github.com/users/SiruzMammadli/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/SiruzMammadli/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'TurgutAliyev',
    id: 101804166,
    node_id: 'U_kgDOBhFohg',
    avatar_url: 'https://avatars.githubusercontent.com/u/101804166?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/TurgutAliyev',
    html_url: 'https://github.com/TurgutAliyev',
    followers_url: 'https://api.github.com/users/TurgutAliyev/followers',
    following_url:
      'https://api.github.com/users/TurgutAliyev/following{/other_user}',
    gists_url: 'https://api.github.com/users/TurgutAliyev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/TurgutAliyev/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/TurgutAliyev/subscriptions',
    organizations_url: 'https://api.github.com/users/TurgutAliyev/orgs',
    repos_url: 'https://api.github.com/users/TurgutAliyev/repos',
    events_url: 'https://api.github.com/users/TurgutAliyev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/TurgutAliyev/received_events',
    type: 'User',
    site_admin: false,
  },
];
